services:

  backend:
    image: pradeepdumka/test-app-backend:latest
    container_name: test-app-backend
    restart: unless-stopped

    environment:
      HOST: 0.0.0.0
      PORT: 4000
      CLIENT_URL: ${CLIENT_URL}

volumes:
  mongo_data:
