services:

  backend:
    image: pradeepdumka/backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "80:4000"
    environment:
      HOST: 0.0.0.0
      PORT: 4000
      CLIENT_URL: ${CLIENT_URL}

volumes:
  mongo_data:
